### ISSUE TITLE
slack integration

### ISSUE THREAD

**Issue by mrtyler** [darwin-network/slash#14]
Slack is the dominant communication tool. If you can't interop with it do you even exist??

**Comment by slingamn** [comment]
I actually seriously considered this a few weeks ago and then realized (duh) that this would result in our IRC conversations being relayed into Slack's system. The problem isn't interoperating with a proprietary protocol, it's exposing plaintext user data to third-party infrastructure. If we could do this in a way that provided end-to-end encryption between irc.darwin.network and the Slack users, we would.

"Plaintext user data never touches third-party infrastructure" is a core principle, e.g., we run our own Kiwi gateway rather than using https://kiwiirc.com/enablekiwi
