### ISSUE TITLE
irc server-like, listening on default irc port without ssl, just tells you how to connect

### ISSUE THREAD

**Issue by edmund-huber** [darwin-network/slash#5]
Some MOTD like:

```
Hi!
To connect, you must use TLS.
The password is t###he^passw&ord (remove non-alphanumerics).
```

Then it hangs up.

**Comment by slingamn** [comment]
Implementation notes:

1. I'm fine sending the unobfuscated server password in plaintext --- it's just a roadblock for ordinary port probes. The server password is public information.
1. Let's send both complete connection information (the host/port/tls/password/channel that we display on the website) and a link to the website itself.
1. We may not want to send the regular MOTD numerics because some clients suppress the MOTD by default. We might have better luck with something like NOTICE.

**Comment by slingamn** [comment]
xinetd's `banner_fail` feature might be a good fit for this.

**Comment by DanielOaks** [comment]
note: Advertising an [STS policy](https://ircv3.net/specs/extensions/sts.html) on this plaintext server which matches one on the server running on 6697 may let clients with newer software automagically use 6697 without needing to do anything manual (depending on the duration time and how often they connect after getting the initial policy, of course). Depends on having a non-self-signed cert on 6697 and possibly pushing a CAP LS reply line after dumping that MOTD to the user (if the 6667 software isn't a full ircd)

**Comment by slingamn** [comment]
I'm going to implement this in oragono, but I have mixed feelings about deploying it to darwin, because I feel like opening port 6667 inherently makes the server more vulnerable to passive monitoring (e.g., if some client connects and immediately tries to send a SASL PLAIN auth blob).

**Comment by slingamn** [comment]
This is a wontfix.
